services:
  - type: web
    name: pawcare-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false # Render will ask you for this value during setup
      - key: CLIENT_URL
        sync: false # You can add this later once Vercel is done
      - key: PORT
        value: "5000"
